<a href="https://colab.research.google.com/github/jyothishri184/Machine-Learning-Algorithms/blob/main/1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
l1=[1,2,3,4]
l1.append(1)
print(l1)

[1, 2, 3, 4, 1]


In [ ]:
l1.append([1,2,3])
l1

[1, 2, 3, 4, 1, [1, 2, 3]]

In [ ]:
l1.insert(0,0)
l1

[0, 1, 2, 3, 4, 1, [1, 2, 3]]

In [ ]:
l1.remove(1)
l1

[0, 2, 3, 4, 1, [1, 2, 3]]

In [ ]:
l1.remove(4)
l1

[0, 2, 3, 1, [1, 2, 3]]

In [ ]:
res=[[i for i in sub if i!=3]for sub in [[2],[2,3,4],[3,3],[34,5,3]]]
res

[[2], [2, 4], [], [34, 5]]

In [ ]:
l1.pop()
l1

[0, 2, 3, 1]

NUMPY

In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3]) #1D

In [ ]:
arr.shape

(3,)

In [ ]:
arr=np.array([[1,2,3],[3,4,5],[1,2,3],[3,5]])  #try jagged arr
print(arr)
arr

[list([1, 2, 3]) list([3, 4, 5]) list([1, 2, 3]) list([3, 5])]


<ipython-input-11-cd80586dad4d>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr=np.array([[1,2,3],[3,4,5],[1,2,3],[3,5]])  #try jagged arr


array([list([1, 2, 3]), list([3, 4, 5]), list([1, 2, 3]), list([3, 5])],
      dtype=object)

In [ ]:
print(arr)
arr.shape

[list([1, 2, 3]) list([3, 4, 5]) list([1, 2, 3]) list([3, 5])]


(4,)

In [ ]:
np.arange(3,7)

array([3, 4, 5, 6])

In [ ]:
res=np.arange(36,89)
print(res)

[36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59
 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88]


In [ ]:
print(type(res))

<class 'numpy.ndarray'>


In [ ]:
a=np.array([1,2,3,4],dtype=float)
print(type(a))
a

<class 'numpy.ndarray'>


array([1., 2., 3., 4.])

In [ ]:
a=np.array([1,2,3,4],dtype=np.float64)
print(type(a))
a

<class 'numpy.ndarray'>


array([1., 2., 3., 4.])

In [ ]:
a.dtype

dtype('float64')

In [ ]:
a=np.array([1,2,3,4],dtype=np.int64)
print(type(a))
print(a)
a.dtype

<class 'numpy.ndarray'>
[1 2 3 4]


dtype('int64')

In [ ]:
np.random.random(4)

array([0.29458395, 0.35535314, 0.96380674, 0.61324725])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.ones((3,2,4),dtype=np.int64)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [ ]:
np.zeros((4,2,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [ ]:
np.full((2,3),8) #constant

array([[8, 8, 8],
       [8, 8, 8]])

In [ ]:
np.eye(4) #identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye(4,dtype=np.int64)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
np.linspace(4,7,num=5) #implicit

array([4.  , 4.75, 5.5 , 6.25, 7.  ])

In [ ]:
(7-4)/4 #formula (x2-x1)/(n-1) linspace

0.75

In [ ]:
lst = np.array([[1,2,3],[3,4,5],[7,8,9],[10,11,12]])
print(lst)

[[ 1  2  3]
 [ 3  4  5]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
lst[0][2]

3

In [ ]:
lst[0:3] #explicit, rows:rows expicit

array([[1, 2, 3],
       [3, 4, 5],
       [7, 8, 9]])

In [ ]:
lst[0:2,0] #row,column

array([1, 3])

In [ ]:
lst[0:3,0:2]

array([[1, 2],
       [3, 4],
       [7, 8]])

In [ ]:
lst[2,2] #lst[2][2]

9

In [ ]:
lst[2][2]=2
lst

array([[ 1,  2,  3],
       [ 3,  4,  5],
       [ 7,  8,  2],
       [10, 11, 12]])

In [ ]:
b=lst[0:3,0:5]
b

array([[1, 2, 3],
       [3, 4, 5],
       [7, 8, 2]])

In [ ]:
b[0][2]=111
lst

array([[  1,   2, 111],
       [  3,   4,   5],
       [  7,   8,   2],
       [ 10,  11,  12]])

In [ ]:
b #refernce is copied so changes in copied arr impacts original array

array([[  1,   2, 111],
       [  3,   4,   5],
       [  7,   8,   2]])

In [ ]:
print(lst[1])

[3 4 5]


In [ ]:
print(lst[2,:])

[7 8 2]


In [ ]:
print(lst[[3],:])

[[10 11 12]]


In [ ]:
row_1=lst[1]
row_2=lst[1:3]
row_3=lst[[1],:]
row_4 = lst[2,2]
row_5=np.array([5])
print(row_1,row_1.shape)
print(row_2,row_2.shape)
print(row_3,row_3.shape)
print(row_4,row_4.shape)
print(row_5,row_5.shape)

[3 4 5] (3,)
[[3 4 5]
 [7 8 2]] (2, 3)
[[3 4 5]] (1, 3)
2 ()
[5] (1,)


In [ ]:
lst

array([[  1,   2, 111],
       [  3,   4,   5],
       [  7,   8,   2],
       [ 10,  11,  12]])

In [ ]:
col_1=lst[:,1]
col_2=lst[1:3,1:3]

print(col_1,col_1.shape)
print(col_2,col_2.shape)

[ 2  4  8 11] (4,)
[[4 5]
 [8 2]] (2, 2)


Boolean array indexing

In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
bool_idx = (a>2)
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [ ]:
a[bool_idx]

array([3, 4, 5, 6])

In [ ]:
a.shape

(3, 2)

ARG FUNCTION

In [ ]:
a = np.array([1,8,9,-3,2,4,7,-8])
print(np.argmax(a)) #index of the maximum element

2


In [ ]:
print(np.argmin(a))

7


In [ ]:
print(np.argsort(a)) #smallest -8 index-7 nextsmallest -3 index-3

[7 3 0 4 5 6 1 2]


In [ ]:
print(a)
print(np.where(a>5)[0])

[ 1  8  9 -3  2  4  7 -8]
[1 2 6]


In [ ]:
a = np.array([[1,8,9,-3],[2,4,7,-8]])
print(np.where(a>4)[1]) #doubt

[1 2 2]


In [ ]:
a = np.array([[3,2,1],[1,5,4],[8,8,7]])
print(a)
b = np.sort(a,axis=1,kind= "quicksort")
print(b) #rowwise sort

[[3 2 1]
 [1 5 4]
 [8 8 7]]
[[1 2 3]
 [1 4 5]
 [7 8 8]]


In [ ]:
c = np.sort(a,axis=0,kind= "quicksort")
print(c) #col wise

[[1 2 1]
 [3 5 4]
 [8 8 7]]


In [ ]:
d = np.sort(a) #default axis=1 rowwise
print(d)

[[1 2 3]
 [1 4 5]
 [7 8 8]]


In [ ]:
data = np.array([1,2,3,4,4,5,6,7,7,8,4,12])
ans1 = data.reshape(3,4)
print(ans1)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  4 12]]


In [ ]:
ans2 = data.reshape(4,3)
print(ans2)

[[ 1  2  3]
 [ 4  4  5]
 [ 6  7  7]
 [ 8  4 12]]


In [ ]:
print(ans2)
ans3 = ans2.reshape(-1,1)
print(ans3)
ans4 = ans2.reshape(-1)
print(ans4)

[[ 1  2  3]
 [ 4  4  5]
 [ 6  7  7]
 [ 8  4 12]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 7]
 [ 8]
 [ 4]
 [12]]
[ 1  2  3  4  4  5  6  7  7  8  4 12]


BROADCASTING

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([1])
print(arr1+arr2) #[1] is reshaped as [1,1,1] for adding is called broadcasting
print(arr1-arr2)

[2 3 4]
[0 1 2]


In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4])
arr1+arr2 #operands can be broadcasting only using (3+1) or (4+1) not (3+2)

array([5, 6, 7])

In [ ]:
arr1*arr2

array([ 4,  8, 12])

In [ ]:
arr1 = np.array([[1,2,3],[6,7,8],[3,2,1]])
arr2 = np.array([[4],[5],[6]])
arr1+arr2

array([[ 5,  6,  7],
       [11, 12, 13],
       [ 9,  8,  7]])

In [ ]:
arr1*arr2

array([[ 4,  8, 12],
       [30, 35, 40],
       [18, 12,  6]])

In [ ]:
print(arr1)
arr1.T #transpose

[[1 2 3]
 [6 7 8]
 [3 2 1]]


array([[1, 6, 3],
       [2, 7, 2],
       [3, 8, 1]])